# Global Setting for the Database
# PageSize, StartRID, etc..
RECORD_SIZE = 8
MAX_RID = 100000000
MAX_PAGE_NUM = 16
META_DATA_COL_NUM = 4
MAX_LONGINT = 2147483647
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3

def init():
    pass